/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelreservation;

import static hotelreservation.customerInfo.selectedRoomType;

/**
 *
 * @author Lissett
 */
public class completeProcess extends javax.swing.JFrame {
    
    private String firstName;
private String lastName;
private String guestNum;
private String phoneNumber;
private String emailAddress;
private String checkIn;
private String checkOut;
int selectedCheckIn; 
int selectedCheckOut;
  int confirmationNum;  
  
  
  
static String selectedRoomType;

int totalPrice;
int roomPrice;
int dayCount;
int features;  
  
int monthIn;
int dayIn;
int yearIn;

 String finalCheckIn;
 String finalCheckOut;
 
 String cardName;
 String cardNum;
 String cardExp;
 String cardCvc;
  
  

    /**
     * Creates new form completeProcess
     */

  /**
   * 
   * @param fName
   * @param lName
   * @param gNum
   * @param phone
   * @param email
   * @param number
   * @param first
   * @param last
   * @param guest
   * @param phone
   * @param email
   * @param number
   * @param type
   * @param dateIn
   * @param dateOut
     * @param cName
     * @param cNum
     * @param cardEx
     * @param cardC
   * @param total
   * @param roomAmount
   * @param days
   * @param feats
   * @param timeIn
   * @param timeOut 
   */
 
 
 
 
 public completeProcess(int number) {
     initComponents();
     resNumHolder.setText("" + number);
 }
         
 /*
    public completeProcess(String first, String last, String guest, String phone, String email, int number, String type, String dateIn, String dateOut, int total, int roomAmount, int days, int feats, String timeIn, String timeOut, String cName, String cNum, String cardEx, String cardC) {
        initComponents();
               firstName = first;
               lastName = last;
               guestNum = guest;
               phoneNumber = phone;
               emailAddress = email;
               resNumHolder.setText("" + number);
               selectedRoomType = type;
                checkIn = dateIn;
                checkOut = dateOut;
                totalPrice = total;
                roomPrice = roomAmount;
                dayCount = days;
                features = feats;
                finalCheckIn = timeIn;
                finalCheckOut = timeOut;
                cardName = cName;
                cardNum = cNum;
                cardExp = cardEx;
                cardCvc = cardC;
    }

 
 */
 
  //  completeProcess(String firstName, String lastName, String guestNum, String phoneNumber, String emailAddress, int confirmationNum) {
  //      throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  //  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resNumHolder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thank you");

        jLabel2.setText("Here is your room number: ");

        resNumHolder.setText("resNum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(resNumHolder)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(resNumHolder))
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(completeProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(completeProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(completeProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(completeProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        //        new completeProcess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel resNumHolder;
    // End of variables declaration//GEN-END:variables
}
