/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelreservation;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author 12137
 */
public class customerInfo extends javax.swing.JFrame {
private static customerInfo customer= null;
//for now, entries will be taken as strings
//next sprint we will some type to int only
private String firstName;
private String lastName;
private String guestNum;
private String phoneNumber;
private String emailAddress;
private String checkIn;
private String checkOut;
        
    /**
     * Creates new form customerInfo
     */
    public customerInfo() {
        initComponents();
    }
    
//method not being used.. not sure if we need this.    
    public static synchronized customerInfo getInstance(){
        if(customer == null){
            customer = new customerInfo();   
        }
        return customer;
    }
        
    public static void writeToFile(String first, String last, String numOfGuest, String phone, String email, String inDate, String outDate) throws FileNotFoundException, IOException{
        //opening excel file
        String excelFilePath = "hotel_info.xlsx";
        File file = new File(excelFilePath); 
            try (FileInputStream excelFile = new FileInputStream(file)) {
                
                XSSFWorkbook workbook = new XSSFWorkbook(excelFile);
                XSSFSheet sheet = workbook.getSheet("Sheet1"); 
                                
                int lastRow = sheet.getLastRowNum();
                //last row needs to be incremted, otherwise will overwrite
                lastRow++;
                Row row = sheet.createRow(lastRow);
                //Customer info
                //for next sprint: create a for loop or manually add all fields
                Cell entry0 = row.createCell(0);
                entry0.setCellValue(first);
                
                Cell entry1 = row.createCell(1);
                entry1.setCellValue(last);
                
                Cell entry2 = row.createCell(2);
                entry2.setCellValue(numOfGuest);
                
                Cell entry3 = row.createCell(3);
                entry3.setCellValue(phone);
                
                Cell entry4 = row.createCell(4);
                entry4.setCellValue(email);
                
                Cell entry5 = row.createCell(5);
                entry5.setCellValue(inDate);
                
                Cell entry6 = row.createCell(6);
                entry6.setCellValue(outDate);
                
                excelFile.close();
                
                //this is what writes/saves the file
                FileOutputStream outFile = new FileOutputStream(new File(excelFilePath));
                workbook.write(outFile);
                outFile.close();
                
            }
    }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        customerInputPanel = new javax.swing.JPanel();
        enterInfo = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        phoneNumLabel = new javax.swing.JLabel();
        emailAddLabel = new javax.swing.JLabel();
        checkInLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        guestNumLabel = new javax.swing.JLabel();
        enterFirstName = new javax.swing.JFormattedTextField();
        confirmationButton = new java.awt.Button();
        enterLastName = new javax.swing.JFormattedTextField();
        enterGuestNum = new javax.swing.JFormattedTextField();
        enterPhoneNumber = new javax.swing.JFormattedTextField();
        enterEmailAddress = new javax.swing.JFormattedTextField();
        enterCheckIn = new javax.swing.JFormattedTextField();
        enterCheckOut = new javax.swing.JFormattedTextField();

        jFormattedTextField3.setText("jFormattedTextField1");
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jFormattedTextField7.setText("jFormattedTextField1");
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterInfo.setText("To begin, enter the following information:");

        firstNameLabel.setText("First name:");

        lastNameLabel.setText("Last name:");

        phoneNumLabel.setText("Phone number:");

        emailAddLabel.setText("Email address: ");

        checkInLabel.setText("Check-in date:");

        checkOutLabel.setText("Check out date:");

        guestNumLabel.setText("Number of guests:");

        enterFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterFirstNameActionPerformed(evt);
            }
        });

        confirmationButton.setBackground(new java.awt.Color(255, 255, 255));
        confirmationButton.setLabel("Confirm Your Reservation");
        confirmationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationButtonActionPerformed(evt);
            }
        });

        enterLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLastNameActionPerformed(evt);
            }
        });

        enterGuestNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterGuestNumActionPerformed(evt);
            }
        });

        enterPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPhoneNumberActionPerformed(evt);
            }
        });

        enterEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterEmailAddressActionPerformed(evt);
            }
        });

        enterCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterCheckInActionPerformed(evt);
            }
        });

        enterCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterCheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInputPanelLayout = new javax.swing.GroupLayout(customerInputPanel);
        customerInputPanel.setLayout(customerInputPanelLayout);
        customerInputPanelLayout.setHorizontalGroup(
            customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInputPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerInputPanelLayout.createSequentialGroup()
                        .addComponent(phoneNumLabel)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerInputPanelLayout.createSequentialGroup()
                        .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkInLabel)
                            .addComponent(emailAddLabel))
                        .addGap(18, 18, 18)))
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enterCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(enterPhoneNumber)
                    .addComponent(enterEmailAddress))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(customerInputPanelLayout.createSequentialGroup()
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerInputPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerInputPanelLayout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(checkOutLabel)
                                .addGap(18, 18, 18)
                                .addComponent(enterCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(customerInputPanelLayout.createSequentialGroup()
                                    .addComponent(guestNumLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(enterGuestNum, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(customerInputPanelLayout.createSequentialGroup()
                                    .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(firstNameLabel)
                                        .addComponent(lastNameLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(enterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(customerInputPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(enterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(customerInputPanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(confirmationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        customerInputPanelLayout.setVerticalGroup(
            customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addGap(26, 26, 26)
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(26, 26, 26)
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterGuestNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guestNumLabel))
                .addGap(26, 26, 26)
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumLabel))
                .addGap(26, 26, 26)
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddLabel))
                .addGap(26, 26, 26)
                .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(customerInputPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(customerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkInLabel)
                            .addComponent(checkOutLabel)))
                    .addComponent(enterCheckOut)
                    .addComponent(enterCheckIn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(confirmationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        confirmationButton.getAccessibleContext().setAccessibleName("Confirm Your Reservation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void enterFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterFirstNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enterFirstNameActionPerformed

    private void confirmationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationButtonActionPerformed
        
    try {
        // TODO add your handling code here:
        //store text into declared variable
        //variable = textfieldboxname.getText()
        firstName = enterFirstName.getText();
        lastName = enterLastName.getText();
        guestNum = enterGuestNum.getText(); //no getInt exists, have to use Integer parse
        phoneNumber = enterPhoneNumber.getText();
        emailAddress = enterEmailAddress.getText();
        checkIn = enterCheckIn.getText();
        checkOut = enterCheckOut.getText();
        
        writeToFile(firstName,lastName, guestNum, phoneNumber,emailAddress,checkIn,checkOut);
        
    } catch (IOException ex) {
        Logger.getLogger(customerInfo.class.getName()).log(Level.SEVERE, null, ex);
    }
         //links this panel to hotelRoom via button click
        confirmation confirm = new confirmation();
        confirm.show();
        dispose();
    }//GEN-LAST:event_confirmationButtonActionPerformed

    private void enterLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLastNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enterLastNameActionPerformed

    private void enterGuestNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterGuestNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterGuestNumActionPerformed

    private void enterPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterPhoneNumberActionPerformed

    private void enterEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterEmailAddressActionPerformed

    private void enterCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterCheckInActionPerformed

    private void enterCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterCheckOutActionPerformed

    
    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerInfo().setVisible(true);
            }
        });

        
       // String name = customerInfo.getInstance().firstName;
       // String last = customerInfo.getInstance().lastName;
      
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JLabel checkOutLabel;
    private java.awt.Button confirmationButton;
    private javax.swing.JPanel customerInputPanel;
    private javax.swing.JLabel emailAddLabel;
    private javax.swing.JFormattedTextField enterCheckIn;
    private javax.swing.JFormattedTextField enterCheckOut;
    private javax.swing.JFormattedTextField enterEmailAddress;
    private javax.swing.JFormattedTextField enterFirstName;
    private javax.swing.JFormattedTextField enterGuestNum;
    private javax.swing.JLabel enterInfo;
    private javax.swing.JFormattedTextField enterLastName;
    private javax.swing.JFormattedTextField enterPhoneNumber;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel guestNumLabel;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel phoneNumLabel;
    // End of variables declaration//GEN-END:variables
}
