/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelreservation;

/**
 *
 * @author 12137
 */
public class hotelRooms extends javax.swing.JFrame {

    /**
     * Creates new form hotelRooms
     */
    public hotelRooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomSelection = new javax.swing.ButtonGroup();
        selectRoomLabel = new javax.swing.JLabel();
        kingLakeIMG = new javax.swing.JLabel();
        doubleBedIMG = new javax.swing.JLabel();
        kingBalconyIMG = new javax.swing.JLabel();
        nextButton = new java.awt.Button();
        doubleBedsSelected = new javax.swing.JRadioButton();
        kingBalconySelected = new javax.swing.JRadioButton();
        KingLakeSelected = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectRoomLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectRoomLabel.setText("Select a room:");

        kingLakeIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelPictues/King Bed Lake View.JPG"))); // NOI18N

        doubleBedIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelPictues/Double Beds.JPG"))); // NOI18N

        kingBalconyIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelPictues/King Bed Balcony.JPG"))); // NOI18N

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nextButton.setLabel("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        roomSelection.add(doubleBedsSelected);
        doubleBedsSelected.setText("Double Queen Beds");
        doubleBedsSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleBedsSelectedActionPerformed(evt);
            }
        });

        roomSelection.add(kingBalconySelected);
        kingBalconySelected.setText("King Bed with Balcony");

        roomSelection.add(KingLakeSelected);
        KingLakeSelected.setText("King Bed with Lake View");
        KingLakeSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KingLakeSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kingLakeIMG)
                    .addComponent(kingBalconyIMG)
                    .addComponent(doubleBedIMG))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(selectRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kingBalconySelected)
                            .addComponent(doubleBedsSelected)
                            .addComponent(KingLakeSelected))
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(selectRoomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doubleBedIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(kingBalconyIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(doubleBedsSelected)
                        .addGap(108, 108, 108)
                        .addComponent(kingBalconySelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kingLakeIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(KingLakeSelected)
                        .addGap(88, 88, 88)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        customerInfo custInfo = new customerInfo();
        custInfo.show();
        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void doubleBedsSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleBedsSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doubleBedsSelectedActionPerformed

    private void KingLakeSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KingLakeSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KingLakeSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotelRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotelRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotelRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotelRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotelRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton KingLakeSelected;
    private javax.swing.JLabel doubleBedIMG;
    private javax.swing.JRadioButton doubleBedsSelected;
    private javax.swing.JLabel kingBalconyIMG;
    private javax.swing.JRadioButton kingBalconySelected;
    private javax.swing.JLabel kingLakeIMG;
    private java.awt.Button nextButton;
    private javax.swing.ButtonGroup roomSelection;
    private javax.swing.JLabel selectRoomLabel;
    // End of variables declaration//GEN-END:variables
}
