/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelreservation;

import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.util.*;
/**
 *
 * @author josea
 */

public class selecting_room extends javax.swing.JFrame {

    /**
     * Creates new form selecting_room
     */
    public selecting_room() {
        
        String outMsg = "An additional selection it will cost $50!";
    JOptionPane.showMessageDialog(null, outMsg);
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BreakfastPlanft = new javax.swing.JCheckBox();
        SmokingAreaft = new javax.swing.JCheckBox();
        PetFriendlyft = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        PlaygroundAreaft = new javax.swing.JCheckBox();
        gymArea = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        ExtraPillowsft = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PoolAccessAreaft = new javax.swing.JCheckBox();
        ExtraTowelsft = new javax.swing.JCheckBox();
        ExtraHangersft = new javax.swing.JCheckBox();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BreakfastPlanft.setText("Breakfast plan");

        SmokingAreaft.setText("Smoking area");
        SmokingAreaft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmokingAreaftActionPerformed(evt);
            }
        });

        PetFriendlyft.setText("Pet friendly");

        jLabel1.setText("Please choose 3 options for your room");

        PlaygroundAreaft.setText("Playground area");

        gymArea.setText("Gym area");

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ExtraPillowsft.setText("Extra pillows");

        jLabel4.setText("Choose 1 area");

        jLabel5.setText("Choose 1 feature");

        PoolAccessAreaft.setText("Pool access");

        ExtraTowelsft.setText("Extra towels");

        ExtraHangersft.setText("Extra Hangers");
        ExtraHangersft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraHangersftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel4)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SmokingAreaft)
                            .addComponent(gymArea)
                            .addComponent(PlaygroundAreaft)
                            .addComponent(PoolAccessAreaft))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExtraPillowsft)
                            .addComponent(PetFriendlyft)
                            .addComponent(BreakfastPlanft)
                            .addComponent(ExtraTowelsft)
                            .addComponent(ExtraHangersft))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gymArea)
                    .addComponent(PetFriendlyft))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SmokingAreaft)
                    .addComponent(ExtraPillowsft))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlaygroundAreaft)
                    .addComponent(BreakfastPlanft))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExtraTowelsft)
                    .addComponent(PoolAccessAreaft))
                .addGap(18, 18, 18)
                .addComponent(ExtraHangersft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        customerInfo custInfo = new customerInfo();
        custInfo.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SmokingAreaftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmokingAreaftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmokingAreaftActionPerformed

    private void ExtraHangersftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraHangersftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraHangersftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selecting_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selecting_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selecting_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selecting_room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selecting_room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BreakfastPlanft;
    private javax.swing.JCheckBox ExtraHangersft;
    private javax.swing.JCheckBox ExtraPillowsft;
    private javax.swing.JCheckBox ExtraTowelsft;
    private javax.swing.JCheckBox PetFriendlyft;
    private javax.swing.JCheckBox PlaygroundAreaft;
    private javax.swing.JCheckBox PoolAccessAreaft;
    private javax.swing.JCheckBox SmokingAreaft;
    private javax.swing.JCheckBox gymArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
