/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelreservation;

import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 12137
 * Module name or Class name in the Design: welcome.java
Date of the code: 4/26/22
Programmer's name: Yashira Almanza & 
Brief description of the class/module 
In this class the four main actions are Make a Reservation , Cancel Reservation, Sign Up and Log In
Brief explanation of important functions in each class, including its input values and output values 
Making a Reservation-
Cancel reservation-
Sign Up- In this function the customer is able to enter the email address to register in order to get rewards for the next reservation. 
Log In- This function ables the customer to enter the email that customer registered if they sign up. If the email address is found in the file, they get to pick the rewards that they want and will be stored in the database.
Any important data structure in class/methods 
Sign Up-
registerCustomer()
logIn()

 */


public class welcome extends javax.swing.JFrame {
String email;
String outMsg;
    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservationButton = new java.awt.Button();
        welcomeLabel = new javax.swing.JLabel();
        hotelIMG = new javax.swing.JLabel();
        reservationButton1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        checkReservationButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        reservationButton.setBackground(new java.awt.Color(255, 255, 255));
        reservationButton.setLabel("Make a Reservation\n");
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcomeLabel.setText("WELCOME ");

        hotelIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelPictues/hotelImage.jpg"))); // NOI18N

        reservationButton1.setActionCommand("Cancel Reservation ");
        reservationButton1.setBackground(new java.awt.Color(255, 255, 255));
        reservationButton1.setLabel("Cancel Reservation");
        reservationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("To get Rewards: Sign In or Log in");

        checkReservationButton.setActionCommand("Cancel Reservation ");
        checkReservationButton.setBackground(new java.awt.Color(255, 255, 255));
        checkReservationButton.setLabel("Check Reservation");
        checkReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReservationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(welcomeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reservationButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(3, 3, 3)
                                    .addComponent(checkReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(hotelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(reservationButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerCustomer() throws IOException{
        //The customer register with their email 
      FileWriter fw = new FileWriter("membershipHotel.txt",true);
      PrintWriter out = new PrintWriter(fw);
   
      email = JOptionPane.showInputDialog("Enter your email: "); 
      out.println(email);
   
      // Close the file.
      out.close();
      
      outMsg = "You are all done!"; //welcome with the character pressed
      JOptionPane.showMessageDialog(null,outMsg);
}
    
    /**the method for the customer to be able to enter the email 
    if email is found in the file text, then the customer is able to pick 
    a reward */
    private void logIn() throws IOException{
        
       // boolean win = false;
      boolean done = false;
      
      Scanner sc1;
      sc1 = new Scanner(System.in);
      
      String input = null;
     
      email = JOptionPane.showInputDialog("Enter your email: ");
      
      boolean flag = false;
      int count = 0;
      
        //directory of the flat text
        //creating the flat text to keep the customers info
      Scanner sc2 = new Scanner(new FileInputStream("membershipHotel.txt"));
      
      //Looks in the file if the email is there
      while(sc2.hasNextLine()) {
         String line = sc2.nextLine();
         System.out.println(line);
         
         if(line.contains(email)) {
            flag = true;
            count = count+1;
         }
      }
      
      if(flag) {
         //System.out.println("You are a member!");
         JOptionPane.showMessageDialog(null, "You are a member!");
         JOptionPane.showMessageDialog(null, "You get to choose a REWARD!");
         String[] buttons = {"Massage Coupon","10% discount","An Upgrade","A towel"};// the buttons' names (parameter)
         int cont = JOptionPane.showOptionDialog(null,"Select a Reward", "Options of Rewards:", 0, JOptionPane.INFORMATION_MESSAGE, null, buttons, buttons[0]); 
         //System.out.println("Number of occurrences is: "+count);
         outMsg = "You Chose " + buttons[cont] +". Yay!"; //welcome with the character pressed
         JOptionPane.showMessageDialog(null,outMsg);
         JOptionPane.showMessageDialog(null, "Thank you for being a member!");
         
      } else {
         JOptionPane.showMessageDialog(null, "You are nor a member "); 
         //System.out.println("You are nor a member, Do you want to become one?");
         int option = JOptionPane.showConfirmDialog(null, "Do you want to become one?"); // using will press "yes" or " no" or "cancel"
         
         switch (option){
             //if the customer says "yes" to register 
            case 0: 
               JOptionPane.showMessageDialog(null, "Great! Let's get you register"); 
               FileWriter fw = new FileWriter("membershipHotel.txt",true);
               PrintWriter out = new PrintWriter(fw);
               email = JOptionPane.showInputDialog("Enter your email: "); 
               out.println(email);
            
            // Close the file.
               out.close();
               
               outMsg = "You are all done!"; //welcome with the character pressed
               JOptionPane.showMessageDialog(null,outMsg);
               break;
             
               //if the customer says "no" to register 
            case 1: 
               JOptionPane.showMessageDialog(null, "Ok, thank you for being a customer! You can continue as a guest.");
               done = true;
               break;
           
            //if the person did not choose any options 
            default: 
               JOptionPane.showMessageDialog(null, "Thank you!");
         }
         
      }
   }

  
    
   
    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
        // TODO add your handling code here:
        hotelRooms rooms = new hotelRooms();
        //opens new jframe window
        rooms.show(); 
        //closes this window
        dispose();
    }//GEN-LAST:event_reservationButtonActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void reservationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButton1ActionPerformed
        // TODO add your handling code here:
        new cancelRoom().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reservationButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            registerCustomer();
        } catch (IOException ex) {
            Logger.getLogger(welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        logIn();
        } catch (IOException ex) {
            Logger.getLogger(welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void checkReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReservationButtonActionPerformed
        // TODO add your handling code here:
        new checkReservation().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkReservationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button checkReservationButton;
    private javax.swing.JLabel hotelIMG;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private java.awt.Button reservationButton;
    private java.awt.Button reservationButton1;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
